### ISSUE TITLE
Implement Junction Failure

### ISSUE THREAD

**Issue by hollyrebecca** [keemyb/SEPR-LYS-A3#2]

**Comment by hollyrebecca** [comment]
Complete Junction Failure by Friday 30/01/15
Complete Obstacle Mid-Track by Wednesday 04/02/2015
Complete Obstacles by Friday 06/02/2015

**Comment by keemyb** [comment]
Junction Failure completed in fa7ccd1a0c1afdf732346a09119840c3299d49f2
